import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/general/Header";
import { Footer } from "@/components/general/Footer";
import { ThemeProvider } from "@/components/provider/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
